# Generated by Django 5.1.3 on 2024-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band_alter_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='l',
            field=models.CharField(default='m', max_length=20),
            preserve_default=False,
        ),
    ]
